# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestEbay():
    def __init__(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_ebay(self):
        self.driver.get("https://secure.pushauction.com/")
        self.driver.set_window_size(945, 1020)
        self.driver.find_element(By.ID, "txtUserID").click()
        self.driver.find_element(By.ID, "txtUserID").click()
        element = self.driver.find_element(By.ID, "txtUserID")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "btnLogin").click()
        element = self.driver.find_element(By.LINK_TEXT, "4797")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "Nav103").click()
        self.driver.find_element(By.LINK_TEXT, "在线").click()
        self.driver.find_element(By.ID, "txtKeyword").click()
        self.driver.find_element(By.ID, "txtKeyword").send_keys("251959314797")
        self.driver.find_element(By.ID, "btnSearch").click()
        element = self.driver.find_element(By.ID, "btnSearch")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "rpeBayListLog_lblActionMenu_0").click()
        self.driver.find_element(By.LINK_TEXT, "在线编辑").click()
        self.driver.switch_to.frame(2)
        self.driver.find_element(By.ID, "chkSelQTY").click()
        self.driver.find_element(By.ID, "btnGoEdit").click()
        self.driver.find_element(By.CSS_SELECTOR, "#panQTY .control-label").click()
        self.driver.find_element(By.ID, "txtAvailableQTY").click()
        self.driver.find_element(By.ID, "txtAvailableQTY").send_keys("5")
        self.driver.find_element(By.ID, "btnGoToConfirm").click()
        self.driver.find_element(By.ID, "btnUpdate").click()


m = TestEbay()
m.test_ebay()